qemu-system-aarch64 \
  -accel hvf \
  -cpu cortex-a57 \
  -M virt,highmem=off \
  -m 3G \
  -smp 3 \
  -drive file=/opt/homebrew/Cellar/qemu/7.2.0/share/qemu/edk2-aarch64-code.fd,if=pflash,format=raw,readonly=on \
  -drive if=none,file=ubuntu.img,format=qcow2,id=hd0 \
  -device virtio-blk-device,drive=hd0,serial="dummyserial" \
  -device virtio-net-device,netdev=net0 \
  -netdev user,id=net0 \
  -vga none \
  -device ramfb \
  -cdrom ubuntu-20.04.5-live-server-arm64.iso \
  -device usb-ehci \
  -device usb-kbd \
  -device usb-mouse \
  -usb \
  -nographic
